### ISSUE TITLE
Demos are missing BBD normalized classes

### ISSUE THREAD

**Issue by PlusInsta** [MrRobotjs/BetterDocs#196]
The demos for themes on BetterDocs are missing BandagedBetterDiscord normalized classes. Any themes that rely on those to work will appear as broken.

![Demo showing Discord+](https://user-images.githubusercontent.com/38794586/54343410-027ad880-463f-11e9-9ae2-4398e46895b3.png)

**Comment by MrRobotjs** [comment]
Currently working on an option to opt-in for bdd normalized classes or discord Obfuscated classes. Also this is the old github repo. Use this one instead betterdocs-react.

**Comment by PlusInsta** [comment]
Ah, that makes sense. I didn't realize this was an old repository.
I'll just close this issue then. Thanks for answering.
